require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe Cities::WeathersController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Weather. As you add validations to Weather, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {temp: 1, city_id: 1}
  }

  let(:invalid_attributes) {
    {temp: -1000}
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WeathersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #new" do
    it "returns a success response" do
      get :new, params: {city_id: 1}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #edit" do
    it "returns a success response" do
      weather = Weather.create! valid_attributes
      get :edit, params: {id: weather.to_param, city_id: 1}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Weather" do
        expect {
          post :create, params: {weather: valid_attributes, city_id: 1}, session: valid_session
        }.to change(Weather, :count).by(1)
      end

      it "redirects to city show" do
        post :create, params: {weather: valid_attributes, city_id: 1}, session: valid_session
        expect(response).to redirect_to(city_path(id: 1))
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'new' template)" do
        post :create, params: {weather: invalid_attributes, city_id: 1}, session: valid_session
        expect(response).to be_successful
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {temp: 2}
      }

      it "updates the requested weather" do
        weather = Weather.create! valid_attributes
        put :update, params: {id: weather.to_param, weather: new_attributes, city_id: 1}, session: valid_session
        weather.reload
        expect(weather.temp).to eq(2)
      end

      it "redirects to the city show" do
        weather = Weather.create! valid_attributes
        put :update, params: {id: weather.to_param, weather: valid_attributes, city_id: 1}, session: valid_session
        expect(response).to redirect_to(city_path(id: 1))
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'edit' template)" do
        weather = Weather.create! valid_attributes
        put :update, params: {id: weather.to_param, weather: invalid_attributes, city_id: 1}, session: valid_session
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested weather" do
      weather = Weather.create! valid_attributes
      expect {
        delete :destroy, params: {id: weather.to_param, city_id: 1}, session: valid_session
      }.to change(Weather, :count).by(-1)
    end

    it "redirects to the city show" do
      weather = Weather.create! valid_attributes
      delete :destroy, params: {id: weather.to_param, city_id: 1}, session: valid_session
      expect(response).to redirect_to(city_path(id: 1))
    end
  end

end
